language: python

python:
  - "2.7"
  - "3.3"

env:
  - NUMPY_VERSION=1.8.0
  - NUMPY_VERSION=1.7.1
  - NUMPY_VERSION=1.6.2

matrix:
  exclude:
    - python: "3.3"
      env: NUMPY_VERSION=1.6.2

before_install:
  - pip install pip --upgrade
  - pip install setuptools --upgrade
  - pip install pytest --upgrade

install:
  - pip install numpy==$NUMPY_VERSION
  - pip install scipy==0.13
  - pip install matplotlib==1.3.1

script: py.test